### ISSUE TITLE
The environment you run this project is? 

### ISSUE THREAD

**Issue by Alijin** [waseef3277/Neural-Style-Transfer_URDU#1]
I am very interested in this flied and want to run this project. But I do not know what your run environment is

**Comment by Alijin** [comment]
@waseef3277  when I run it, there is a bug , i do not know how to handle it 
'ValueError: zero-size array to reduction operation minimum which has no identity'?

**Comment by waseef-ullah** [comment]
The environment for preprocessing is python 2 and for tensorflow related work you need python 3.

**Comment by waseef-ullah** [comment]
@Alijin Can you please post full error message?

**Comment by Alijin** [comment]
@waseef3277 
Traceback (most recent call last):
  File "F:/Neural-Style-Transfer_URDU-master/transfer.py", line 344, in <module>
    tf.app.run()
  File "D:\python-3.5.4-amd64\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "F:/Neural-Style-Transfer_URDU-master/transfer.py", line 223, in main
    render_frame(bitmaps, frame_dir, steps)
  File "F:/Neural-Style-Transfer_URDU-master/transfer.py", line 109, in render_frame
    return render_fonts_image(x, frame_path, img_per_row)
  File "F:\Neural-Style-Transfer_URDU-master\utils.py", line 29, in render_fonts_image
    misc.toimage(canvas).save(path)
  File "D:\python-3.5.4-amd64\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\scipy\misc\pilutil.py", line 337, in toimage
    cmin=cmin, cmax=cmax)
  File "D:\python-3.5.4-amd64\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python35\site-packages\scipy\misc\pilutil.py", line 93, in bytescale
    cmin = data.min()
  File "D:\python-3.5.4-amd64\lib\site-packages\numpy\core\_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

This is the full error messages. And could you mind telling me your email-address please?

**Comment by waseef-ullah** [comment]
Looks like you are not passing a correct path in argument for source and target fonts. Please follow the description I provided. 
Sure you can contact me on kwaseef6030@gmail.com

**Comment by Alijin** [comment]
@waseef3277 Thank a million！
